import { pgTable, text, boolean, integer, jsonb, serial, timestamp, primaryKey } from 'drizzle-orm/pg-core';
import { generateId } from '@colyseus/core';
import type { TableEntry } from './registry.ts';

// ---------------------------------------------------------------------------
// Spreadable base columns — users can spread these into their own pgTable
// calls to extend with custom fields.
//
//   import { columns } from '@colyseus/database';
//   const users = pgTable('my_users', {
//     ...columns.pg.users,
//     displayName: text('display_name'),
//   });
// ---------------------------------------------------------------------------

export const userColumns = {
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  email: text('email'),
  passwordHash: text('password_hash'),
  anonymous: boolean('anonymous').notNull().default(true),
  anonymousId: text('anonymous_id'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  // Ban state — null bannedUntil means not banned. A future timestamp
  // means banned through that instant; the AuthService.findByEmail check
  // rejects sign-in while bannedUntil > now.
  bannedUntil: timestamp('banned_until'),
  bannedReason: text('banned_reason'),
  // Session revocation counter — see schemas/sqlite.ts for the design.
  tokenVersion: integer('token_version').notNull().default(0),
};

export const configColumns = {
  key: text('key').primaryKey(),
  value: jsonb('value'),
  version: integer('version').notNull().default(1),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
};

export const cloudSaveColumns = {
  userId: text('user_id').notNull(),
  slot: integer('slot').notNull(),
  version: integer('version').notNull().default(1),
  data: jsonb('data'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
};

export const leaderboardColumns = {
  // Auto-generated by default. Devs who want a meaningful handle (e.g.
  // "weekly_2025") still pass it explicitly via `db.leaderboards.ensure(id, name)`
  // — the upsert respects whatever id is supplied.
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  name: text('name').notNull(),
};

export const leaderboardEntryColumns = {
  boardId: text('board_id').notNull(),
  userId: text('user_id').notNull(),
  season: text('season').notNull().default('global'),
  score: integer('score').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
};

export const analyticsEventColumns = {
  id: serial('id').primaryKey(),
  userId: text('user_id'),
  name: text('name').notNull(),
  props: jsonb('props'),
  ts: timestamp('ts').notNull().defaultNow(),
};

/**
 * Single-table RBAC: one row per user.
 *
 *   role:   'admin' / 'mod' / 'user' — global role.
 *   scopes: collection names this user can act on. Only meaningful for
 *           `role = 'mod'`. See schemas/sqlite.ts for the full design.
 */
export const roleColumns = {
  userId: text('user_id').primaryKey(),
  role: text('role', { enum: ['admin', 'mod', 'user'] as const }).notNull(),
  scopes: jsonb('scopes').$type<string[]>().notNull().$defaultFn(() => []),
};

/**
 * Admin audit log — see schemas/sqlite.ts for full notes.
 *
 * createdAt uses a JS-side `$defaultFn` instead of `defaultNow()` so
 * the timestamp comes from the same clock the test cutoff uses; PG's
 * server-side now() and the JS Date sometimes drift enough to flake
 * `prune(before)` cutoffs by a millisecond.
 */
export const adminAuditColumns = {
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  operatorId: text('operator_id'),
  action: text('action').notNull(),
  resource: text('resource').notNull(),
  targetId: text('target_id'),
  payload: jsonb('payload'),
  createdAt: timestamp('created_at').notNull().$defaultFn(() => new Date()),
};

/**
 * Free-form admin notes attached to a user. Append-only by convention
 * (the service exposes create + delete; no edit), so an audit trail of
 * "Refunded once 2026-04 — Endel" remains stable. authorId is the
 * operator who wrote the note.
 */
export const userNoteColumns = {
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  userId: text('user_id').notNull(),
  authorId: text('author_id'),
  text: text('text').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
};

// ---------------------------------------------------------------------------
// Default table instances — used when the user does NOT provide custom schemas
// ---------------------------------------------------------------------------

export const colyseusUsers = pgTable('colyseus_users', { ...userColumns });

export const colyseusConfigs = pgTable('colyseus_configs', { ...configColumns });

export const colyseusCloudSaves = pgTable('colyseus_cloud_saves', { ...cloudSaveColumns }, (table) => [
  primaryKey({ columns: [table.userId, table.slot] }),
]);

export const colyseusLeaderboards = pgTable('colyseus_leaderboards', { ...leaderboardColumns });

export const colyseusLeaderboardEntries = pgTable(
  'colyseus_leaderboard_entries',
  { ...leaderboardEntryColumns },
  (table) => [primaryKey({ columns: [table.boardId, table.userId, table.season] })],
);

export const colyseusAnalyticsEvents = pgTable('colyseus_analytics_events', { ...analyticsEventColumns });

export const colyseusRoles = pgTable('colyseus_roles', { ...roleColumns });

export const colyseusUserNotes = pgTable('colyseus_user_notes', { ...userNoteColumns });

export const colyseusAdminAudit = pgTable('colyseus_admin_audit', { ...adminAuditColumns });

// ---------------------------------------------------------------------------
// Registry — see ./sqlite.ts SQLITE_TABLES for the design rationale. PG
// declares its own array because GameDatabase loads dialect modules lazily;
// keeping the registry per-dialect preserves that.
// ---------------------------------------------------------------------------

export const PG_TABLES: ReadonlyArray<TableEntry> = [
  { key: 'users',              table: colyseusUsers,              columns: userColumns,            dependsOn: [] },
  { key: 'configs',            table: colyseusConfigs,            columns: configColumns,          dependsOn: [] },
  { key: 'leaderboards',       table: colyseusLeaderboards,       columns: leaderboardColumns,     dependsOn: [] },
  { key: 'analyticsEvents',    table: colyseusAnalyticsEvents,    columns: analyticsEventColumns,  dependsOn: [] },
  { key: 'cloudSaves',         table: colyseusCloudSaves,         columns: cloudSaveColumns,       dependsOn: ['users'] },
  { key: 'leaderboardEntries', table: colyseusLeaderboardEntries, columns: leaderboardEntryColumns, dependsOn: ['users', 'leaderboards'] },
  { key: 'roles',              table: colyseusRoles,              columns: roleColumns,            dependsOn: ['users'] },
  { key: 'userNotes',          table: colyseusUserNotes,          columns: userNoteColumns,        dependsOn: ['users'] },
  { key: 'adminAudit',         table: colyseusAdminAudit,         columns: adminAuditColumns,      dependsOn: [] },
];
