import { sqliteTable, text, integer, primaryKey } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { generateId } from '@colyseus/core';
import type { TableEntry } from './registry.ts';

// ---------------------------------------------------------------------------
// Spreadable base columns — users can spread these into their own sqliteTable
// calls to extend with custom fields.
//
//   import { columns } from '@colyseus/database';
//   const users = sqliteTable('my_users', {
//     ...columns.sqlite.users,
//     displayName: text('display_name'),
//   });
// ---------------------------------------------------------------------------

export const userColumns = {
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  email: text('email'),
  passwordHash: text('password_hash'),
  anonymous: integer('anonymous', { mode: 'boolean' as const }).notNull().default(true),
  anonymousId: text('anonymous_id'),
  createdAt: integer('created_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer('updated_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
  // Ban state — null bannedUntil means not banned. A future timestamp
  // means banned through that instant; the AuthService.findByEmail check
  // rejects sign-in while bannedUntil > now.
  bannedUntil: integer('banned_until', { mode: 'timestamp' as const }),
  bannedReason: text('banned_reason'),
  // Session revocation counter. Bumped on password change or "log out
  // everywhere"; every issued JWT carries the version it was signed
  // with. guard() rejects tokens whose version is stale, invalidating
  // all prior sessions without rotating JWT_SECRET globally.
  tokenVersion: integer('token_version').notNull().default(0),
};

export const configColumns = {
  key: text('key').primaryKey(),
  value: text('value', { mode: 'json' as const }),
  version: integer('version').notNull().default(1),
  updatedAt: integer('updated_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
};

export const cloudSaveColumns = {
  userId: text('user_id').notNull(),
  slot: integer('slot').notNull(),
  version: integer('version').notNull().default(1),
  data: text('data', { mode: 'json' as const }),
  createdAt: integer('created_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer('updated_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
};

export const leaderboardColumns = {
  // Auto-generated by default. Devs who want a meaningful handle (e.g.
  // "weekly_2025") still pass it explicitly via `db.leaderboards.ensure(id, name)`
  // — the upsert respects whatever id is supplied.
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  name: text('name').notNull(),
};

export const leaderboardEntryColumns = {
  boardId: text('board_id').notNull(),
  userId: text('user_id').notNull(),
  season: text('season').notNull().default('global'),
  score: integer('score').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
};

export const analyticsEventColumns = {
  id: integer('id').primaryKey({ autoIncrement: true }),
  userId: text('user_id'),
  name: text('name').notNull(),
  props: text('props', { mode: 'json' as const }),
  ts: integer('ts', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
};

/**
 * Single-table RBAC: one row per user.
 *
 *   role:   'admin' / 'mod' / 'user' — global role.
 *   scopes: collection names this user can act on. Only meaningful for
 *           `role = 'mod'` (admins implicitly cover everything; users
 *           are read-only on whatever the caller passes to `can()`).
 *
 * `scopes` is JSON-encoded so the same shape works in pg (jsonb) and
 * sqlite (text + json mode). Default is the empty array so reads after
 * INSERT-without-scopes don't need to coalesce.
 */
export const roleColumns = {
  userId: text('user_id').primaryKey(),
  role: text('role', { enum: ['admin', 'mod', 'user'] as const }).notNull(),
  scopes: text('scopes', { mode: 'json' as const }).$type<string[]>().notNull().$defaultFn(() => []),
};

/**
 * Admin audit log. Every Create / Update / Delete / custom action that
 * passes through `admin()` records a row here so operators can
 * answer "who edited this config / banned which player". The table is
 * append-only; deletion is a separate, opt-in operation (e.g. a cron
 * that prunes rows older than N days).
 *
 * `payload` is opaque JSON — its shape depends on the action:
 *   create → { row }
 *   update → { before, after }
 *   delete → { row }
 *   custom → { name, args, result }
 */
export const adminAuditColumns = {
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  operatorId: text('operator_id'),
  action: text('action').notNull(),
  resource: text('resource').notNull(),
  targetId: text('target_id'),
  payload: text('payload', { mode: 'json' as const }),
  createdAt: integer('created_at', { mode: 'timestamp_ms' as const })
    .notNull()
    .$defaultFn(() => new Date()),
};

/**
 * Free-form admin notes attached to a user. Append-only by convention
 * (the service exposes create + delete; no edit), so an audit trail of
 * "Refunded once 2026-04 — Endel" remains stable. authorId is the
 * operator who wrote the note.
 *
 * createdAt uses `timestamp_ms` mode so notes added back-to-back keep
 * a stable order — `unixepoch()` only has second precision, which made
 * "newest first" tests flake.
 */
export const userNoteColumns = {
  id: text('id').primaryKey().$defaultFn(() => generateId(21)),
  userId: text('user_id').notNull(),
  authorId: text('author_id'),
  text: text('text').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' as const })
    .notNull()
    .$defaultFn(() => new Date()),
};

// ---------------------------------------------------------------------------
// Default table instances — used when the user does NOT provide custom schemas
// ---------------------------------------------------------------------------

export const colyseusUsers = sqliteTable('colyseus_users', { ...userColumns });

export const colyseusConfigs = sqliteTable('colyseus_configs', { ...configColumns });

export const colyseusCloudSaves = sqliteTable('colyseus_cloud_saves', { ...cloudSaveColumns }, (table) => [
  primaryKey({ columns: [table.userId, table.slot] }),
]);

export const colyseusLeaderboards = sqliteTable('colyseus_leaderboards', { ...leaderboardColumns });

export const colyseusLeaderboardEntries = sqliteTable(
  'colyseus_leaderboard_entries',
  { ...leaderboardEntryColumns },
  (table) => [primaryKey({ columns: [table.boardId, table.userId, table.season] })],
);

export const colyseusAnalyticsEvents = sqliteTable('colyseus_analytics_events', { ...analyticsEventColumns });

export const colyseusRoles = sqliteTable('colyseus_roles', { ...roleColumns });

export const colyseusUserNotes = sqliteTable('colyseus_user_notes', { ...userNoteColumns });

export const colyseusAdminAudit = sqliteTable('colyseus_admin_audit', { ...adminAuditColumns });

/**
 * Matchmaking room cache — sqlite twin of pg's `roomCacheColumns`. See the
 * pg schema for why this is driver-owned and deliberately absent from
 * SQLITE_TABLES. `locked`/`private`/`unlisted` are integer-boolean, and
 * `metadata` is json-mode text so the driver can write/read room metadata
 * as a plain object while still querying it via `json_extract`.
 */
export const roomCacheColumns = {
  roomId: text('room_id').primaryKey(),
  processId: text('process_id'),
  name: text('name').notNull(),
  clients: integer('clients').notNull(),
  maxClients: integer('max_clients').notNull(),
  locked: integer('locked', { mode: 'boolean' as const }),
  private: integer('private', { mode: 'boolean' as const }),
  metadata: text('metadata', { mode: 'json' as const }),
  publicAddress: text('public_address'),
  createdAt: integer('created_at', { mode: 'timestamp' as const }).notNull().default(sql`(unixepoch())`),
  unlisted: integer('unlisted', { mode: 'boolean' as const }),
};

export const colyseusRoomCaches = sqliteTable('colyseus_room_caches', { ...roomCacheColumns });

// ---------------------------------------------------------------------------
// Registry — single source of truth consumed by GameDatabase.boot() for
// schema resolution + table creation. Order is enforced via `dependsOn`
// (topologically sorted at boot); declaration order here is informational.
// ---------------------------------------------------------------------------

export const SQLITE_TABLES: ReadonlyArray<TableEntry> = [
  { key: 'users',              table: colyseusUsers,              columns: userColumns,            dependsOn: [] },
  { key: 'configs',            table: colyseusConfigs,            columns: configColumns,          dependsOn: [] },
  { key: 'leaderboards',       table: colyseusLeaderboards,       columns: leaderboardColumns,     dependsOn: [] },
  { key: 'analyticsEvents',    table: colyseusAnalyticsEvents,    columns: analyticsEventColumns,  dependsOn: [] },
  { key: 'cloudSaves',         table: colyseusCloudSaves,         columns: cloudSaveColumns,       dependsOn: ['users'] },
  { key: 'leaderboardEntries', table: colyseusLeaderboardEntries, columns: leaderboardEntryColumns, dependsOn: ['users', 'leaderboards'] },
  { key: 'roles',              table: colyseusRoles,              columns: roleColumns,            dependsOn: ['users'] },
  { key: 'userNotes',          table: colyseusUserNotes,          columns: userNoteColumns,        dependsOn: ['users'] },
  { key: 'adminAudit',         table: colyseusAdminAudit,         columns: adminAuditColumns,      dependsOn: [] },
];
