language: node_js

cache:
  npm: false

node_js:
  - 12
  - 13

install:
  - 'npm install'

services:
  - redis-server
  - mongodb

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
        chmod +x ./cc-test-reporter;
        ./cc-test-reporter before-build;
    fi

script:
  - npm run tslint
  - npm test

after_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT;
    fi
