packages:
  - bundles/*
  - packages/*
  - packages/better-call/packages/*
  - packages/drivers/*
  - packages/transport/*
  - packages/presence/*
  - packages/serializer/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@fails-components/webtransport-transport-http3-quiche'
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract
  - nx
