/**
 * Ecosystem config for testing PM2 deployment with specific instance count.
 * Auto-generated by test script.
 */
module.exports = {
  apps: [{
    name: 'my-app',
    script: './dummy-server.js',
    instances: 1,
    max_memory_restart: '256M',
  }]
};
