/**
 * PM2 Deployment Test Suite (Mocha)
 *
 * Tests that the post-deploy logic respects the `instances` configuration
 * from ecosystem.config.js and doesn't scale to os.cpus().length.
 *
 * Usage:
 *   npx mocha --import tsx test/pm2-deployment.test.ts --timeout 60000
 */
import pm2 from 'pm2';
import net from 'net';
import { execFile } from 'child_process';
import path from 'path';
import fs from 'fs';
import os from 'os';
import assert from 'assert';

const TEST_DIR = __dirname;
const ECOSYSTEM_CONFIG_PATH = path.join(TEST_DIR, 'ecosystem.config.cjs');
const TEST_NGINX_CONFIG_PATH = path.join(TEST_DIR, 'test_colyseus_servers.conf');
const LISTEN_DELAY_FILE = path.join(TEST_DIR, '.listen-delay-ms');
// what the Cloud panel writes to ~/.colyseus/env/runtime.json
const TEST_RUNTIME_ENV_PATH = path.join(TEST_DIR, 'test_runtime_env.json');

// Path to the local @colyseus/tools package for PM2 module installation
const TOOLS_PACKAGE_PATH = path.resolve(__dirname, '..');

const PM2_APP_NAME = 'my-app';

/**
 * Update ecosystem config with specified number of instances
 */
function updateEcosystemConfig(instances: number, { killTimeout = 2000, maxMemoryRestart = '', env = {} as Record<string, string> } = {}): void {
  const configContent = `/**
 * Ecosystem config for testing PM2 deployment with specific instance count.
 * Auto-generated by test script.
 */
module.exports = {
  apps: [{
    name: '${PM2_APP_NAME}',
    script: './dummy-server.cjs',
    instances: ${instances},
    kill_timeout: ${killTimeout},${maxMemoryRestart ? `\n    max_memory_restart: '${maxMemoryRestart}',` : ''}${Object.keys(env).length ? `\n    env: ${JSON.stringify(env)},` : ''}
  }]
};
`;
  fs.writeFileSync(ECOSYSTEM_CONFIG_PATH, configContent);
}

/**
 * List running apps (excluding @colyseus/tools)
 */
function listApps(): Promise<pm2.ProcessDescription[]> {
  return new Promise((resolve, reject) => {
    pm2.list((err, apps) => {
      if (err) return reject(err);
      const testApps = apps.filter(app => app.name === PM2_APP_NAME);
      resolve(testApps);
    });
  });
}

/**
 * Wait for apps to reach expected count and status
 */
function waitForApps(expectedCount: number, status = 'online', timeout = 15000): Promise<pm2.ProcessDescription[]> {
  return new Promise((resolve, reject) => {
    const startTime = Date.now();

    const check = async () => {
      try {
        const apps = await listApps();
        const matchingApps = apps.filter(app => app.pm2_env?.status === status);

        if (matchingApps.length === expectedCount) {
          resolve(matchingApps);
        } else if (Date.now() - startTime > timeout) {
          reject(new Error(
            `Timeout: Expected ${expectedCount} ${status} apps, got ${matchingApps.length} ` +
            `(total apps: ${apps.length})`
          ));
        } else {
          setTimeout(check, 500);
        }
      } catch (err) {
        reject(err);
      }
    };

    check();
  });
}

/**
 * Wait until no process is mid-transition. Polling beats a fixed sleep: faster
 * on a quick box.
 *
 * The agent replies before its rollout is over: it waits 1.5s for NGINX, then
 * drains the old generation. The pool must stay settled past that wait, or the
 * next deploy lands on top of a rollout that hasn't started draining yet.
 */
async function waitForSettled(timeout = 15000, quietFor = 2500): Promise<void> {
  const startTime = Date.now();
  const transient = new Set(['launching', 'stopping', 'waiting restart']);
  let quietSince = Date.now();

  while (Date.now() - startTime < timeout) {
    const apps = await listApps();
    if (apps.some(app => transient.has(app.pm2_env?.status ?? ''))) {
      quietSince = Date.now();
    } else if (Date.now() - quietSince >= quietFor) {
      return;
    }
    await new Promise(resolve => setTimeout(resolve, 250));
  }
  throw new Error('Timeout: processes never settled');
}

/** Socket ports NGINX currently routes to. */
function nginxUpstreamPorts(): number[] {
  return fs.readFileSync(TEST_NGINX_CONFIG_PATH, 'utf8')
    .split('\n')
    .map(line => line.match(/(\d+)\.sock/)?.[1])
    .filter(Boolean)
    .map(Number)
    .sort((a, b) => a - b);
}

async function waitFor(condition: () => Promise<boolean>, timeout: number, message: () => Promise<string>): Promise<void> {
  const startTime = Date.now();
  while (Date.now() - startTime < timeout) {
    if (await condition()) { return; }
    await new Promise(resolve => setTimeout(resolve, 250));
  }
  throw new Error(`Timeout: ${await message()}`);
}

/** One worker per instance online, nothing mid-transition, NGINX on exactly those. */
async function converged(instances: number): Promise<boolean> {
  const apps = await listApps();
  const transient = ['launching', 'stopping', 'waiting restart', 'errored'];
  if (apps.some(app => transient.includes(app.pm2_env?.status ?? ''))) { return false; }

  const online = apps.filter(app => app.pm2_env?.status === 'online')
    .map(app => 2567 + Number((app.pm2_env as any).NODE_APP_INSTANCE))
    .sort((a, b) => a - b);
  return online.length === instances && nginxUpstreamPorts().join() === online.join();
}

/**
 * Sample the pool until `until` resolves; return the longest stretch (ms) during
 * which NGINX listed no online worker -- when every new player would get a 502.
 */
async function longestDarkStretch(until: Promise<unknown>): Promise<number> {
  let finished = false;
  until.then(() => { finished = true; }, () => { finished = true; });

  let longest = 0;
  let darkSince: number | null = null;

  while (!finished) {
    const apps = await listApps();
    const online = new Set(apps.filter(app => app.pm2_env?.status === 'online')
      .map(app => 2567 + Number((app.pm2_env as any).NODE_APP_INSTANCE)));
    const routable = nginxUpstreamPorts().some(port => online.has(port));

    if (routable) {
      darkSince = null;
    } else {
      darkSince ??= Date.now();
      longest = Math.max(longest, Date.now() - darkSince);
    }
    await new Promise(resolve => setTimeout(resolve, 200));
  }
  return longest;
}

async function describePool(): Promise<string> {
  const apps = await listApps();
  const pool = apps.map(app => `${(app.pm2_env as any).NODE_APP_INSTANCE}:${app.pm2_env?.status}`).join(' ');
  return `pool [${pool}], nginx [${nginxUpstreamPorts()}]`;
}

/**
 * Clean up all test processes
 */
function cleanup(): Promise<void> {
  return new Promise((resolve) => {
    pm2.delete(PM2_APP_NAME, () => resolve());
  });
}

/**
 * Get fresh shared module (clears cache)
 */
function getSharedModule() {
  delete require.cache[require.resolve('../pm2/shared.cjs')];
  return require('../pm2/shared.cjs');
}

/**
 * Launch the agent script as the @colyseus/tools module, without waiting for
 * it to register its action -- what `pm2 ping` leaves behind on boot.
 */
function launchPostDeployAgent(): Promise<void> {
  return new Promise((resolve, reject) => {
    const agentPath = path.resolve(TOOLS_PACKAGE_PATH, 'pm2/post-deploy-agent.cjs');
    pm2.start({
      name: '@colyseus/tools',
      script: agentPath,
      cwd: TOOLS_PACKAGE_PATH,
      time: true,
      // the agent resolves the NGINX path at require-time, in its own process
      env: { NGINX_CONFIG_FILE: TEST_NGINX_CONFIG_PATH, COLYSEUS_RUNTIME_ENV_FILE: TEST_RUNTIME_ENV_PATH },
    }, (err) => err ? reject(err) : resolve());
  });
}

/**
 * Install @colyseus/tools as a PM2 module by starting the agent script directly
 */
async function installPostDeployAgent(): Promise<void> {
  await launchPostDeployAgent();
  // Wait for the module to initialize
  await new Promise(resolve => setTimeout(resolve, 2000));
}

/**
 * Run the real `colyseus-post-deploy` script from `cwd`, as a deploy does.
 */
function runPostDeployScript(cwd: string): Promise<string> {
  return new Promise((resolve) => {
    execFile(process.execPath, [path.resolve(TOOLS_PACKAGE_PATH, 'post-deploy.cjs')], {
      cwd,
      env: { ...process.env, NGINX_CONFIG_FILE: TEST_NGINX_CONFIG_PATH },
    }, (err, stdout, stderr) => resolve(`${stdout}${stderr}${err ? String(err) : ''}`));
  });
}

/** The real `colyseus-post-deploy`, timed: a reply it misses would hang it. */
async function deployWithScript(): Promise<{ output: string; seconds: number }> {
  const startedAt = Date.now();
  const output = await runPostDeployScript(TEST_DIR);
  return { output, seconds: (Date.now() - startedAt) / 1000 };
}

/**
 * Uninstall @colyseus/tools PM2 module
 */
function uninstallPostDeployAgent(): Promise<void> {
  return new Promise((resolve) =>
      pm2.delete('@colyseus/tools', () => resolve()));
}

/**
 * Trigger post-deploy action via the PM2 module
 * This mimics what `colyseus-post-deploy` script does
 */
function triggerPostDeploy(cwd: string, ecosystemPath: string): Promise<{ success: boolean; message?: string }> {
  return new Promise((resolve, reject) => {
    (pm2 as any).trigger('@colyseus/tools', 'post-deploy', `${cwd}:${ecosystemPath}`, (err: Error | null, result: any) => {
      if (err) {
        return reject(err);
      }
      const returnData = result?.[0]?.data?.return;
      if (returnData?.success === false) {
        return reject(new Error(returnData?.message || 'Post-deploy failed'));
      }
      resolve(returnData || { success: true });
    });
  });
}

describe('PM2 Deployment', function () {
  this.timeout(60000); // 60 second timeout for all tests

  const EXPECTED_INSTANCES = 1;

  before(async function () {
    console.log(`\n  System info:`);
    console.log(`    CPU cores: ${os.cpus().length}`);
    console.log(`    Expected instances: ${EXPECTED_INSTANCES}`);
    console.log(`    Test directory: ${TEST_DIR}`);
    console.log(`    Test NGINX config: ${TEST_NGINX_CONFIG_PATH}\n`);

    // Update ecosystem config
    updateEcosystemConfig(EXPECTED_INSTANCES);

    // writeNginxConfig() only writes when the target already exists
    fs.writeFileSync(TEST_NGINX_CONFIG_PATH, '');

    // Connect to PM2
    await new Promise<void>((resolve, reject) => {
      pm2.connect((err) => {
        if (err) return reject(err);
        resolve();
      });
    });

    // Clean up any existing test processes
    await cleanup();

    // Install @colyseus/tools as PM2 module
    console.log('    Installing @colyseus/tools PM2 module...');
    await installPostDeployAgent();
    console.log('    PM2 module installed successfully.\n');
  });

  after(async function () {
    await cleanup();

    // Uninstall @colyseus/tools PM2 module
    console.log('    Uninstalling @colyseus/tools PM2 module...');
    await uninstallPostDeployAgent();

    // Clean up test files
    if (fs.existsSync(TEST_NGINX_CONFIG_PATH)) {
      fs.unlinkSync(TEST_NGINX_CONFIG_PATH);
    }

    pm2.disconnect();
  });

  beforeEach(function (done) {
    // Small delay between tests
    setTimeout(done, 500);
  });

  describe('Fresh Deployment', function () {
    it(`should start exactly ${1} instance(s) on first deploy`, async function () {
      // Clean slate
      await cleanup();

      // Trigger post-deploy via PM2 module (first deploy - will start apps)
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);

      // Wait for apps to be online
      const apps = await waitForApps(EXPECTED_INSTANCES);

      console.log(`      Running instances: ${apps.length}`);
      apps.forEach(app => {
        console.log(`        - Instance ${(app.pm2_env as any)?.NODE_APP_INSTANCE}: PID ${app.pid}`);
      });

      assert.strictEqual(
        apps.length,
        EXPECTED_INSTANCES,
        `Expected ${EXPECTED_INSTANCES} instances, got ${apps.length}`
      );
    });
  });

  describe('Continuous Deployment (reload)', function () {
    it(`should maintain exactly ${1} instance(s) after reload`, async function () {
      // Trigger post-deploy via PM2 module (simulates re-deploy with reload)
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);

      // Wait a bit for reload to complete
      await new Promise(resolve => setTimeout(resolve, 2000));

      // Wait for apps to be online
      const apps = await waitForApps(EXPECTED_INSTANCES);

      console.log(`      Running instances: ${apps.length}`);
      apps.forEach(app => {
        console.log(`        - Instance ${(app.pm2_env as any)?.NODE_APP_INSTANCE}: PID ${app.pid}`);
      });

      assert.strictEqual(
        apps.length,
        EXPECTED_INSTANCES,
        `Expected ${EXPECTED_INSTANCES} instances, got ${apps.length}`
      );
    });
  });

  describe('Multiple Consecutive Deployments', function () {
    const DEPLOY_COUNT = 5;

    // A rolling deploy is briefly meant to hold both generations at once, so the
    // ceiling is the peak -- not `instances`. What must not happen is the total
    // creeping up by one per deploy, which is how a 1-worker app reached 29.
    const PEAK = getSharedModule().peakProcesses(EXPECTED_INSTANCES);

    it(`should not grow past the rolling-deploy peak over ${DEPLOY_COUNT} deploys`, async function () {
      // start from a known pool, not whatever the previous describe left behind
      await cleanup();
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
      await waitForApps(EXPECTED_INSTANCES);

      for (let i = 1; i <= DEPLOY_COUNT; i++) {
        await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
        await waitForSettled();

        // what the inactive-socket monitor did: restart anything it read as dead
        const stopped = (await listApps()).filter(app => app.pm2_env?.status === 'stopped');
        await Promise.all(stopped.map(app =>
          new Promise<void>(resolve => pm2.restart(app.pm_id!, () => resolve()))));

        const apps = await listApps();
        console.log(`      Deployment ${i}/${DEPLOY_COUNT}: ${apps.length} process(es)`);

        assert.ok(
          apps.length <= PEAK,
          `After deployment ${i}: ${apps.length} processes, peak is ${PEAK}`
        );
      }
    });

    it(`should settle back to exactly ${EXPECTED_INSTANCES} online instance(s)`, async function () {
      // the monitor left a surplus worker online; the next deploy converges
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
      await waitForSettled();

      const apps = await waitForApps(EXPECTED_INSTANCES, 'online', 30000);

      assert.strictEqual(apps.length, EXPECTED_INSTANCES);
    });

    it('should give every worker its own instance number and NGINX upstream', async function () {
      // the agent's own NODE_APP_INSTANCE used to leak into the workers it
      // started, so they all claimed instance 0 -- and the same socket
      await waitForSettled();
      const online = await waitForApps(EXPECTED_INSTANCES, 'online', 30000);

      const instances = online.map(app => Number((app.pm2_env as any).NODE_APP_INSTANCE));
      assert.strictEqual(new Set(instances).size, instances.length, `duplicate instances: ${instances}`);

      // NGINX may briefly keep an extra upstream while a restarted process
      // drains (it skips a dead socket), so the contract is: distinct entries,
      // never more than the rolling-deploy peak, and the live socket included.
      const upstreams = fs.readFileSync(TEST_NGINX_CONFIG_PATH, 'utf8').trim().split('\n').filter(Boolean);
      const PEAK = getSharedModule().peakProcesses(EXPECTED_INSTANCES);
      assert.ok(upstreams.length >= 1 && upstreams.length <= PEAK, `upstreams: ${upstreams}`);
      assert.strictEqual(new Set(upstreams).size, upstreams.length, `duplicate upstreams: ${upstreams}`);
      const liveSock = `server unix:/run/colyseus/${2567 + instances[0]}.sock;`;
      assert.ok(upstreams.includes(liveSock), `live sock ${liveSock} missing from: ${upstreams}`);
    });
  });

  describe('Worker restarted by a rollout', function () {
    // With 2 instances a rollout spawns one worker, restarts the first old one
    // (instance 0) into the new generation and stops the second (instance 1).
    const INSTANCES = 2;

    async function deployTwoWorkers(env: Record<string, string>) {
      await cleanup();
      updateEcosystemConfig(INSTANCES, { killTimeout: 30000, env });
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
      await waitForApps(INSTANCES);
      await waitForSettled();
    }

    after(async function () {
      await cleanup();
      updateEcosystemConfig(EXPECTED_INSTANCES);
    });

    it('should be routed to once back, even when it drains longer than the stopped one', async function () {
      // longer than PM2 takes to report the other one stopped (~5s)
      await deployTwoWorkers({ DRAIN_INSTANCE: '0', DRAIN_MS: '10000' });

      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);

      // instance 0 back from its restart, instance 2 the spawned one
      await waitFor(async () => {
        const online = (await listApps()).filter(app => app.pm2_env?.status === 'online');
        return online.length === INSTANCES && nginxUpstreamPorts().length === INSTANCES;
      }, 30000, describePool);
      const routedAt = fs.statSync(TEST_NGINX_CONFIG_PATH).mtimeMs;

      await waitForSettled();
      assert.deepStrictEqual(nginxUpstreamPorts(), [2567, 2569], await describePool());

      // the rollout's final reconcile found nothing to change: no NGINX reload
      assert.strictEqual(fs.statSync(TEST_NGINX_CONFIG_PATH).mtimeMs, routedAt);
    });

    it('should be routed to while another worker is still draining', async function () {
      await deployTwoWorkers({ DRAIN_INSTANCE: '1', DRAIN_MS: '15000' });

      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);

      // PM2 reports a stop ~5s after the process exits, so the restart takes ~6s
      await waitFor(async () => nginxUpstreamPorts().includes(2567), 12000, describePool);

      const draining = (await listApps()).find(app => (app.pm2_env as any).NODE_APP_INSTANCE === 1);
      assert.strictEqual(draining?.pm2_env?.status, 'stopping', await describePool());
    });
  });

  [1, 2, 4].forEach((INSTANCES) => describe(`Overlapping deploys (${INSTANCES} process(es))`, function () {
    this.timeout(180000);

    after(async function () {
      await cleanup();
      updateEcosystemConfig(EXPECTED_INSTANCES);
    });

    it('should take turns, and settle on one worker per instance', async function () {
      await cleanup();
      updateEcosystemConfig(INSTANCES);
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
      await waitForApps(INSTANCES);
      await waitForSettled();

      // a webhook deploy and a manual one landing together
      const deployedAt = Date.now();
      const deploys = await Promise.all([deployWithScript(), deployWithScript(), deployWithScript()]);

      // each one gets an answer -- its own -- instead of hanging
      deploys.forEach(({ output, seconds }) => {
        assert.match(output, /Post-deploy success/, output);
        assert.ok(seconds < 30, `post-deploy took ${seconds}s: ${output}`);
      });
      // settled, and on the newest deploy -- including one that waited for a slot
      await waitFor(async () => {
        if (!(await converged(INSTANCES))) { return false; }
        const online = (await listApps()).filter(app => app.pm2_env?.status === 'online');
        return online.every(app => (app.pm2_env as any).pm_uptime >= deployedAt);
      }, 90000, describePool);

      const apps = await listApps();
      const online = apps.filter(app => app.pm2_env?.status === 'online');
      const instances = online.map(app => Number((app.pm2_env as any).NODE_APP_INSTANCE)).sort((a, b) => a - b);

      assert.ok(!apps.some(app => app.pm2_env?.status === 'errored'), await describePool());
      assert.strictEqual(online.length, INSTANCES, await describePool());
      assert.strictEqual(new Set(instances).size, INSTANCES, await describePool());
      assert.deepStrictEqual(nginxUpstreamPorts(), instances.map(i => 2567 + i), await describePool());
    });
  }));

  [1, 2, 4].forEach((INSTANCES) => describe(`Deploy while the previous one drains (${INSTANCES} process(es))`, function () {
    // two drains back to back, plus the waiting rollout's own
    this.timeout(180000);

    after(async function () {
      await cleanup();
      updateEcosystemConfig(EXPECTED_INSTANCES);
    });

    async function twoDeploysDuringDrain(maxMemoryRestart = '') {
      await cleanup();
      updateEcosystemConfig(INSTANCES, { killTimeout: 60000, maxMemoryRestart, env: { DRAIN_INSTANCE: 'all', DRAIN_MS: '10000' } });
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
      await waitForApps(INSTANCES);
      await waitForSettled();

      const scenario = (async () => {
        await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
        await new Promise(resolve => setTimeout(resolve, 4000));

        // the first rollout's old generation is still draining
        const secondAt = Date.now();
        const second = await deployWithScript();
        assert.ok(second.seconds < 15, `post-deploy took ${second.seconds}s: ${second.output}`);

        // the second deploy's version goes live: every online worker started after it
        await waitFor(async () => {
          if (!(await converged(INSTANCES))) { return false; }
          const online = (await listApps()).filter(app => app.pm2_env?.status === 'online');
          return online.every(app => (app.pm2_env as any).pm_uptime >= secondAt);
        }, 60000, describePool);

        return second;
      })();

      const dark = await longestDarkStretch(scenario);
      return { dark, second: await scenario };
    }

    it('should keep a worker routable', async function () {
      // starts above the peak or waits, depending on this machine's free RAM
      const { dark } = await twoDeploysDuringDrain();
      assert.ok(dark < 1000, `no routable worker for ${dark}ms`);
    });

    it('should wait for a draining process when there is no memory to spare', async function () {
      // a ceiling no machine can cover: never start above the peak
      const { dark, second } = await twoDeploysDuringDrain('512G');
      assert.ok(dark < 1000, `no routable worker for ${dark}ms`);
      // answered at once, which pm2.trigger() could miss and hang on
      assert.match(second.output, /until a draining one exits/, second.output);
    });
  }));

  describe('Slow boot', function () {
    after(async function () {
      await cleanup();
      updateEcosystemConfig(EXPECTED_INSTANCES);
    });

    it('should not route to a new worker before it listens', async function () {
      await cleanup();
      updateEcosystemConfig(EXPECTED_INSTANCES);
      await triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);
      await waitForApps(EXPECTED_INSTANCES);
      await waitForSettled();

      // the new code boots for longer than PM2's own 3s wait for 'ready'
      fs.writeFileSync(LISTEN_DELAY_FILE, '5000');
      const before = nginxUpstreamPorts();
      const deploy = triggerPostDeploy(TEST_DIR, ECOSYSTEM_CONFIG_PATH);

      // the moment NGINX switches, the new worker must already accept connections
      let switched: number[] = before;
      await waitFor(async () => {
        switched = nginxUpstreamPorts();
        return switched.join() !== before.join();
      }, 20000, describePool);

      const port = 43000 + (switched[0] - 2567);
      const listening = await new Promise<boolean>((resolve) => {
        const socket = net.connect(port, '127.0.0.1', () => { socket.end(); resolve(true); });
        socket.on('error', () => resolve(false));
      });
      assert.ok(listening, `NGINX routed to ${switched} before instance ${switched[0] - 2567} was listening`);

      await deploy;
      await waitForSettled();
    });

    afterEach(function () {
      fs.rmSync(LISTEN_DELAY_FILE, { force: true });
    });
  });

  describe('Boot', function () {
    it('should wait for an agent that is still starting instead of falling back', async function () {
      await cleanup();
      await uninstallPostDeployAgent();

      // colyseus-boot runs `pm2 ping && colyseus-post-deploy`: the agent is
      // launched, but hasn't registered its action yet
      await launchPostDeployAgent();
      const output = await runPostDeployScript(TEST_DIR);

      assert.doesNotMatch(output, /legacy/, output);
      assert.match(output, /Post-deploy success/, output);

      // only the agent applies the Cloud defaults (the legacy script starts the raw file)
      const apps = await waitForApps(EXPECTED_INSTANCES);
      assert.strictEqual((apps[0].pm2_env as any).wait_ready, true);
    });
  });

  describe('Cloud panel variables', function () {
    const CLOUD_ECOSYSTEM_PATH = path.join(TEST_DIR, 'test_cloud_env.config.cjs');

    before(function () {
      fs.writeFileSync(CLOUD_ECOSYSTEM_PATH, `module.exports = { apps: [{
        name: '${PM2_APP_NAME}', script: './dummy-server.cjs', kill_timeout: 2000,
        instances: Number(process.env.CLOUD_TEST_WORKERS || 1),
      }] };\n`);
    });

    after(async function () {
      await cleanup();
      fs.rmSync(CLOUD_ECOSYSTEM_PATH, { force: true });
      fs.rmSync(TEST_RUNTIME_ENV_PATH, { force: true });
    });

    it('should evaluate the ecosystem file with them, on the first deploy and after', async function () {
      await cleanup();

      fs.writeFileSync(TEST_RUNTIME_ENV_PATH, JSON.stringify({ CLOUD_TEST_WORKERS: '2' }));
      await triggerPostDeploy(TEST_DIR, CLOUD_ECOSYSTEM_PATH);
      await waitForApps(2, 'online', 30000);

      fs.writeFileSync(TEST_RUNTIME_ENV_PATH, JSON.stringify({ CLOUD_TEST_WORKERS: '1' }));
      await triggerPostDeploy(TEST_DIR, CLOUD_ECOSYSTEM_PATH);
      await waitForSettled();
      await waitForApps(1, 'online', 30000);
    });

    it('should not put them in the processes\' env (the app reads .env.cloud)', async function () {
      const apps = await listApps();
      assert.ok(apps.length > 0);
      for (const app of apps) {
        assert.strictEqual((app.pm2_env as any).env?.CLOUD_TEST_WORKERS, undefined);
        assert.strictEqual((app.pm2_env as any).CLOUD_TEST_WORKERS, undefined);
      }
    });
  });

  describe('Config Instances Property', function () {
    it('should preserve user-specified instances value in config', async function () {
      const cpuCount = os.cpus().length;

      if (cpuCount <= EXPECTED_INSTANCES) {
        this.skip();
        return;
      }

      const shared = getSharedModule();
      const config = await shared.getAppConfig(ECOSYSTEM_CONFIG_PATH);

      console.log(`      CPU count: ${cpuCount}`);
      console.log(`      Config instances: ${config.apps[0].instances}`);

      assert.strictEqual(
        config.apps[0].instances,
        EXPECTED_INSTANCES,
        `Config instances should be ${EXPECTED_INSTANCES}, got ${config.apps[0].instances}`
      );
    });

    it('should NOT default to os.cpus().length when instances is specified', async function () {
      const cpuCount = os.cpus().length;

      if (cpuCount === EXPECTED_INSTANCES) {
        this.skip();
        return;
      }

      const shared = getSharedModule();
      const config = await shared.getAppConfig(ECOSYSTEM_CONFIG_PATH);

      assert.notStrictEqual(
        config.apps[0].instances,
        cpuCount,
        `Config instances should NOT be ${cpuCount} (os.cpus().length)`
      );
    });
  });
});
